# --- Required options --- #

# Name of Jekyll Theme
remote_theme: daattali/beautiful-jekyll@5.0.0

# Name of website
title: 8-Bit Cat's Personal Website

# Author
author: 8itCat

# --- List of links in the navigation bar --- #

navbar-links:
  About Me: "About Me"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"

# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/img/avatar.png"

# --- Socials --- #

social-network-links:
  email: "avaq9970@gmail.com"
  github: 8itCat
  twitter: 8itCat
  reddit: u/QueenVengeance

# --- Other --- #

exclude:
  - README.md
