# --- Required options --- #

# Name of Jekyll Theme
remote_theme: daattali/beautiful-jekyll@5.0.0

# Name of website
title: 8-Bit Cat's Personal Website

# Author
author: 8itCat

# --- List of links in the navigation bar --- #

navbar-links:
  About Me: "About Me"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"
